### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/MI-000-SS00-000-js-localstorage-wMUDce#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://mi-000-ss00-000-js-localstorage-wmudce-KatieMFritz.surge.sh/) and meets the following criteria:

- [x] Includes a button, which when clicked, will toggle the website between day and night themes
- [x] When a user changes the theme, their choice is remembered in `localStorage`
- [x] The class on the `body` element is always up-to-date with the current theme (either `day-theme` or `night-theme`) -- you can use `document.body.setAttribute('class', 'some-class-name')` to set the class on the `body`
- [x] When the body has the class `day-theme`, the background of the website is light-colored, with a darker color for the text
- [x] When the body has the class `night-theme`, the background of the website is a very dark color, with a lighter color for the text
- [x] Somewhere on the page, the user is told how many times they've visited the website (starting with `1` the first time)

**Comment by chrisvfritz** [comment]
Bellisima! 😍 :shipit:
